### ISSUE TITLE
Feature: HMR support

### ISSUE THREAD

**Issue by bloody-ux** [solidjs/solid-refresh#12]
What's the plan of HMR support?

**Comment by LXSMNSYC** [comment]
It should reset since the entire component changed. Take note that the HMR isn't really like React where React can re-use the previous component's instance since React has an underlying VDOM, Solid doesn't have any of those. To preserve the state of the component, the state must be "lifted up" meaning the state should be moved to the parent component, specially if the parent itself is located in a different module.

Here's an example on how you'll be able to preserve the state:

```js
// Message.jsx
export default function Message() {
  // Changing this won't affect the parent.
  return <h1>Hello, World</h1>;
}

// App.jsx
function App() {
  const [count, setCount] = createSignal(0);
  setInterval(() => {
    setCount((c) => c + 1);
  }, 1000);
  return (
    <div>
      <h1>Count: {count()}</h1>
      <Message />
    </div>
  );
}
```

**Comment by bloody-ux** [comment]
I see. But for developers, if they are coding `componentA`, they thought it had the state of signals were kept between HMR updates. Most of the time, we are just keeping on adjusting render code and see the UI.

But now, we have to split one component into a `container component` and  a `presentational component` to have HMR work as expected, right?

Here I mean is it possible to implement a new `createSignal` method which can keep state between HMR updates, and replace original `createSignal` method when compiling.

**Comment by ryansolid** [comment]
It's tricky. This is one of the hardest problems I've faced because we have a graph that can span cross files and very difficult to surgically replace parts mid graph. It'd require keeping references to the old signals and tracing through subscriptions and replacing on both sides, that is if you could bank on stability like knowing what happens when the change order etc.. It probably isn't impossible but it is pretty challenging.

**Comment by bloody-ux** [comment]
I see. Solid doesn't (or doesn't need to) keep the 'ownership' of signals for component because there's no component instance.

**Comment by LXSMNSYC** [comment]
and unlike React/Preact/Vue, there's no Fiber architecture that maintains the reference from the past rendered tree. What we do in solid-refresh is for components to replace themselves (by unmounting the old component and mounting the new component) without affecting the ancestor component tree. Take note that there's no perfect solution to this, even react-refresh is fallible to this concept.
