### ISSUE TITLE
Version 0.7.3 fails with Uncaught ReferenceError: _$$registry is not defined

### ISSUE THREAD

**Issue by pedro00dk** [solidjs/solid-refresh#58]
I'm testing some webpack setups solid-refresh, and after updating packages today, I found out that when I update solid-refresh from 0.7.2 to 0.7.3 the page does not load and fails with `Uncaught ReferenceError: _$$registry is not defined`. I did not test on vite though.
If you need more details I can provide a repository for reproduction.

**Comment by lxsmnsyc** [comment]
It only breaks in 0.7.2?

**Comment by pedro00dk** [comment]
I tested all 0.7.x versions, it only breaks on 0.7.3.
Repo: https://github.com/pedro00dk/solid-refresh-webpack-test
The last commit is using 0.7.3, if you `npm start` it, you will get the following error in the browser console:
![image](https://github.com/solidjs/solid-refresh/assets/7131232/2bc61f52-db9e-47a8-b0c0-4aa9494cc0d8)

The reset to previous commit `git reset --hard @~` and run `npm ci` and `npm start`. It will work.

**Comment by pedro00dk** [comment]
By the way, I just saw 0.7.4 was released, the issue is still present.

**Comment by lxsmnsyc** [comment]
<img width="1030" alt="Screenshot 2024-02-16 at 2 24 02 PM" src="https://github.com/solidjs/solid-refresh/assets/4783372/8616476d-bbd5-4a89-bd3f-5c6faebe3e0e">

This is such a very weird issue. It's able to transform `$$refresh` but not for `$$component` and `$$registry`. I recall this same issue happening for other babel plugins because of how, I believe, the TypeScript preset is compiling imports into require calls.
